# Generated by Django 2.0.3 on 2018-04-19 10:43

from django.db import migrations, models
import django.db.models.deletion
import django_getemail.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uid', models.CharField(max_length=20, unique=True)),
                ('raw_email', models.TextField()),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('sender', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('error', 'Error'), ('new', 'New'), ('retrying', 'Retrying'), ('skipped', 'Skipped'), ('processed', 'Processed')], default='new', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=django_getemail.models.upload_to)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='django_getemail.Email')),
            ],
        ),
    ]
