# Generated by Django 2.0.3 on 2018-04-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_getemail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='recipient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
